site_name: Theory of everything
#site_url: https://howallworks.github.io/theoryofeverything/

theme:
    name: 'material'
    language: en
    ###features:
    ###    - navigation.instant
    palette:

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
        
extra:
  alternate:
    - name: English
      link: /theoryofeverything/theoryofeverything/ 
      lang: en
    - name: Русский
      link: /theoryofeverything/ru/theoryofeverything/
      lang: ru
    
    

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  - toc:
      permalink: true

nav:
  - README: README.md
  - Theoryofeverything: theoryofeverything.md
  - theoryofeverythingPracticalC: theoryofeverythingPracticalC.md
  - verificationExperiments: verificationExperiments.md
  - ElementaryParticles: 
      - Quantum graviton: ElementaryParticles/Quantum graviton.md 
      - Quantum photon: ElementaryParticles/Quantum photon.md
  - ParticlesOfStandardModel: 
      - Photon: ParticlesOfStandardModel/Photon.md 
  - TermsOrAbbreviations:      
      - Accretion disk: TermsOrAbbreviations/Accretion disk.md 
      - Albert Einstein: TermsOrAbbreviations/Albert Einstein.md 
      - Blazar: TermsOrAbbreviations/Blazar.md 
      - Elementary particle: TermsOrAbbreviations/Elementary particle.md 
      - GTR: TermsOrAbbreviations/GTR.md 
      - Helicity: TermsOrAbbreviations/Helicity.md 
      - Relativistic jet: TermsOrAbbreviations/Relativistic jet.md 
      - SMBH: TermsOrAbbreviations/SMBH.md 
      - Standard Model: TermsOrAbbreviations/Standard Model.md 
      - Blandford–Znajek process: TermsOrAbbreviations/Blandford–Znajek process.md 
      - Penrose process: TermsOrAbbreviations/Penrose process.md 
      - Hafele–Keating experiment: TermsOrAbbreviations/Hafele–Keating experiment.md
  - Papers:   
      #- UnsolvedTwinParadox: Papers/UnsolvedTwinParadox.md
      - TermTime: Papers/TermTime.md
      - UnsolvedTwinParadoxLight: Papers/UnsolvedTwinParadoxLight.md
      - OnTheNon-probabilisticNatureOfTheUniverse: Papers/OnTheNon-probabilisticNatureOfTheUniverse.md

plugins:
  - search:
      lang: en
      #lang: 
        #- en
        #- ru
  - roamlinks 
  - mermaid2
  - i18n:
      default_language: en
      ######
      default_language_only: false
      ######
      languages:
        - locale: en
          name: English
          default: true
          build: true
          site_name: Theory of everything
          nav_translations:
              Theoryofeverything: Theory of everything
              theoryofeverythingPracticalC: Theory of everything. Practical Consequences
              verificationExperiments: Verification experiments
              README: Foreword
              ElementaryParticles: Elementary particles
              ParticlesOfStandardModel: Particles of Standard Model
              TermsOrAbbreviations: Terms or abbreviations 
              Papers: Papers
              #UnsolvedTwinParadox: Unsolved Twin Paradox
              TermTime: How to define the term "Second" to create a theory of relativity. The concept of absolute time and the universe in general
              UnsolvedTwinParadoxLight: Two great theories based on a common interpretation of interference. What is wrong with wave-particle duality interpretation and the consequences that follow from it
              OnTheNon-probabilisticNatureOfTheUniverse: On the non-probabilistic nature of the universe
        - locale: ru
          name: Русский
          ######
          build: true
          ######
          site_name: Теория всего
          nav_translations:
              Theoryofeverything: Теория всего
              theoryofeverythingPracticalC: Теория всего. Практические последствия
              verificationExperiments: Проверочные эксперименты
              README: Предисловие
              ElementaryParticles: Элементарные частицы
              ParticlesOfStandardModel: Частицы Стандартной модели
              TermsOrAbbreviations: Термины или сокращения 
              Quantum graviton: Квант гравитон 
              Quantum photon: Квант фотон 
              Photon: Фотон 
              Accretion disk: Аккрецио́нный диск 
              Albert Einstein: Альбе́рт Эйнште́йн 
              Blazar: Блаза́р 
              Elementary particle: Элементарная частица 
              GTR: ОТО 
              Helicity: Спиральность 
              Relativistic jet: Релятиви́стская струя 
              SMBH: СМЧД 
              Standard Model: Стандартная модель 
              Blandford–Znajek process: Процесс Блэнфорда — Знаека 
              Penrose process: процесс Пенроуза 
              Hafele–Keating experiment: Эксперимент Хафеле — Китинга 
              Papers: Научные статьи
              #UnsolvedTwinParadox: Неразрешимый Парадокс Близнецов
              TermTime: Как дать определение термину «Секунда», чтобы создать теорию относительности. Концепция абсолютного времени и вселенной в целом
              UnsolvedTwinParadoxLight: Две великие теории, базирующиеся на общей интерпретации интерференции. Что не так с интерпретацией корпускулярно-волнового дуализма и вытекающие из этого последствия 
              OnTheNon-probabilisticNatureOfTheUniverse: О не вероятностной природе Вселенной
              
extra_javascript:
  #- javascripts/mathjax.js
  #- https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  #- https://unpkg.com/mermaid/dist/mermaid.min.js 
  - https://unpkg.com/mermaid@11.5.0/dist/mermaid.min.js
